### ISSUE TITLE
Task list

### ISSUE THREAD

**Issue by jvanheld** [pvhelden/optimize-matrix-GA#1]
# First implementation of optimize-matrix-GA

- [x] **parse_transfac** read a position-specific matrix (PSSM) from a Transfac-formatted file
- [x] **export_pssms** export one or several position-specific scoring matrices in a given format (by default, Transfac)
- [x] **mutate_matrix** generate a series of mutants from a PSSM
- [x] **scan sequences**: run `rsat matrix-scan-quick` with option `-best_hit_per_seq ` on positive and negative sequence sets and collect the respective score tables
- [x] **compute_stats** : assign a score to each PSSM based on its capability to discriminate positive from negative sequences. By default the score will be the Area Under the Receiver Operating Characteristic curve (AuROC) but alternatively it could be the Area Under the Precision Recall curve (AuPR) 
- [x] **select_matrices**: select a subset of the matrices that will survive to the next generation
- [x] **GA**: implement a function that iterate the mutation-scoring-selection cycles
- [x] **command-line arguments**: read the command line arguments and pass them to the relevant functions
- [x] **user doc**: write user doc to be displayed with option *-h*
- [x] **install.md**: write an installation instructions, including dependencies: python libraries, RSAT
- [x] **examples** add examples in the user doc
- [x] **porting on IFB core cluster wth slurm job scheduler**: #25
- [x] **score table**: #24
- [x] #28
- [x] #33
- [x] #36
- [ ] #38
- [ ] Bug with **AuROC and AuPR values in CC field** #23
- [ ] **over-fitting risk**: #27
- [ ] #32
- [ ] #35
- [ ] **matrix trimming or extension** add an option to extend or reduce matrix sizes by adding or deleting a column on the left or right side (randomly) (#14)
- [ ] #39

## Alternative optimization methods

- [ ] **simulated annealing**: implement a simulated annealing algorithm, and add an option to choose the optimisation algorithm (#21), and add an option to choose the optimisation algorithm
- [ ] #31

## Result visualisation

- [ ] **plot-genealogy**: implement a separate tool that takes as input the score matrix produced by optimize-matrices-GA, and produces a plot of the genealogy (parent-children links between successive generations)

## Tests of functionality / relevance

- [ ] **Negative control**: what does it give when the positive sequence sets are both random sequence sets generated with the same background model? 
- [ ] **Auto-discovery**: feed the tool with two relevant sequences (e.g. ChIP-seq for one TF vs other TFs) but with a neutral matrix (residue counts proportional to prior probabilities in each column) -> check if the selected motifs are relevant (match with transcription factor database). Should probably be more interesting with clone-wise rather than population-wise  selection
- [ ] **Convergence** : in a clone-wise selection, feed the program with related but distinct motifs (e.g. the different leaves of a cluster from matrix-clustering), and check if the final motifs (generation 20) are more related between each other than the initial motifs (generation 0). Apply the same at each generation to see the evolution of the distances between motifs. The similarity / distances can be measured with RSAT compare-matrices, and summarized in a similarity / distance matrix. The similarity between motifs can also be visualised with logos in matrix-clustering results.
